version: '3.6'

networks:
  web:
    external: true
  internal:
    external: false

services:
  relay_back_postgres_db:
    container_name: relay_back_postgres_db
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: relay_back
      POSTGRES_DB: relay_back
    volumes:
      - relay_back_volume_postgres_db:/var/lib/postgresql/data
    networks:
      - internal

  relay_back_redis:
    container_name: relay_back_redis
    image: redis:6.2
    restart: unless-stopped
    networks:
      - internal

  relay_back_app:
    container_name: relay_back_app
    image: relay_back_backend:latest
    restart: always
    command: gunicorn --workers 4 --threads 100 --preload -b 0.0.0.0:80 'wsgi:app'
    depends_on:
      - relay_back_postgres_db
    environment:
      CONFIG: main
      SECRET_KEY:
      POSTGRES_PASSWORD:
    volumes:
      - relay_back_volume_firmwares:/srv/firmwares
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.relay.entrypoints=https"
      - "traefik.docker.network=web"
      - "traefik.http.services.relay.loadbalancer.server.port=80"
      - "traefik.http.routers.relay.tls=true"
      - "traefik.http.routers.relay.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.relay.rule=Host(`relay.smarthome-tech.ru`)"
    networks:
      - web
      - internal

volumes:
  relay_back_volume_postgres_db:
  relay_back_volume_firmwares: