"""empty message

Revision ID: 24a1be77387f
Revises: 542dbfec0e27
Create Date: 2024-02-02 21:10:53.451815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24a1be77387f'
down_revision = '542dbfec0e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['api_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.drop_table('api_statuses')
    # ### end Alembic commands ###
