"""empty message

Revision ID: 542dbfec0e27
Revises: b7f16b293bbf
Create Date: 2024-02-02 19:03:42.146193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542dbfec0e27'
down_revision = 'b7f16b293bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
