"""empty message

Revision ID: 56c4b5e5720f
Revises: f232d56447e0
Create Date: 2024-11-05 16:48:03.718258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56c4b5e5720f'
down_revision = 'f232d56447e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.drop_column('system_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
