"""empty message

Revision ID: 6d3cf95d34af
Revises: 9d50319f223f
Create Date: 2024-01-26 18:47:20.354521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3cf95d34af'
down_revision = '9d50319f223f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
