"""empty message

Revision ID: 727fb7391ddc
Revises: 6d3cf95d34af
Create Date: 2024-01-27 16:39:47.352080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727fb7391ddc'
down_revision = '6d3cf95d34af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###
