"""empty message

Revision ID: 97149dde41a4
Revises: 24a1be77387f
Create Date: 2024-02-11 17:10:16.486643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97149dde41a4'
down_revision = '24a1be77387f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('from_device', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['api_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_commands')
    # ### end Alembic commands ###
