"""empty message

Revision ID: 9d50319f223f
Revises: 0d09eaa3c87e
Create Date: 2024-01-24 22:09:01.824465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d50319f223f'
down_revision = '0d09eaa3c87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_firmwares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('num_of_downloads', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['api_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_firmwares')
    # ### end Alembic commands ###
