"""empty message

Revision ID: b7f16b293bbf
Revises: 727fb7391ddc
Create Date: 2024-01-27 17:26:00.896112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7f16b293bbf'
down_revision = '727fb7391ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_info', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('device_type')
        batch_op.drop_column('version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('system_info')

    # ### end Alembic commands ###
