"""empty message

Revision ID: f232d56447e0
Revises: 97149dde41a4
Create Date: 2024-11-05 16:47:38.665516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f232d56447e0'
down_revision = '97149dde41a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_messages')
    op.drop_table('api_statuses')
    op.drop_table('api_commands')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_commands',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('from_device', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['api_devices.id'], name='api_commands_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_commands_pkey')
    )
    op.create_table('api_statuses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['api_devices.id'], name='api_statuses_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_statuses_pkey')
    )
    op.create_table('api_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('from_device', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['api_devices.id'], name='api_messages_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_messages_pkey')
    )
    # ### end Alembic commands ###
